=== replicator-cli/replicator-cli.github.io/apps/pages/github/public/schemas/0.1.0/replicator.workspace-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "WorkspaceConfig",
  "type": "object",
  "required": [
    "apps",
    "name",
    "version"
  ],
  "properties": {
    "$schema": {
      "default": "https://replicator-cli.github.io/schemas/latest/replicator.workspace-schema.json",
      "type": "string"
    },
    "appConfigFilename": {
      "type": [
        "string",
        "null"
      ]
    },
    "apps": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/AppConfig"
      }
    },
    "description": {
      "type": [
        "string",
        "null"
      ]
    },
    "ignore": {
      "description": "Optional list of globs to ignore when installing and for snapshots",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "name": {
      "type": "string"
    },
    "patchFilename": {
      "type": [
        "string",
        "null"
      ]
    },
    "replayConfigFilename": {
      "type": [
        "string",
        "null"
      ]
    },
    "templateConfigFilename": {
      "type": [
        "string",
        "null"
      ]
    },
    "templateFolders": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "variables": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "version": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "AppConfig": {
      "type": "object",
      "required": [
        "path",
        "templates",
        "version"
      ],
      "properties": {
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "path": {
          "type": "string"
        },
        "templates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AppTemplateRequirement"
          }
        },
        "variables": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "version": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "AppTemplateRequirement": {
      "anyOf": [
        {
          "$ref": "#/definitions/AppTemplateRequirementWithoutLabel"
        },
        {
          "$ref": "#/definitions/AppTemplateRequirementWithLabel"
        }
      ]
    },
    "AppTemplateRequirementWithLabel": {
      "description": "This tuple has the template name, install path and the optional install label",
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ],
      "maxItems": 2,
      "minItems": 2
    },
    "AppTemplateRequirementWithoutLabel": {
      "description": "This tuple has the template name and install path",
      "type": "string"
    }
  }
}

=== replicator-cli/replicator-cli.github.io/replicator.workspace.json
{
  "$schema": "https://replicator-cli.github.io/schemas/latest/replicator.workspace-schema.json",
  "name": "replicator-cli.github.io",
  "version": "2024.05.20",
  "apps": {
    "apps/pages/github": {
      "path": "apps/pages/github",
      "version": "2024.05.20",
      "templates": [
        "replicator-cli.github.io/templates/apps/pages/github/honox",
        "replicator-cli.github.io/templates/apps/pages/github/content"
      ]
    },
    "": {
      "path": "",
      "version": "2024.05.20",
      "templates": [
        "replicator-cli.github.io/templates/workspace/root",
        [
          "replicator-cli.github.io/templates/apps/pages/github/workspace",
          "github"
        ]
      ]
    }
  },
  "variables": {
    "NPM_SAVE": "bun add --exact",
    "NPM_SAVE_DEV": "bun add --exact --dev",
    "PACKAGES_PATH": "packages",
    "PACKAGES_SCOPE": "packages",
    "WORKERS_PATH": "apps/workers",
    "WORKERS_SCOPE": "workers",
    "WORKSPACE_NAME": "replicator-cli.github.io",
    "WORKSPACE_SAVE": "bun add --exact",
    "WORKSPACE_SAVE_DEV": "bun add --exact --dev"
  },
  "ignore": [
    ".git",
    ".wrangler",
    "node_modules",
    "bun.lockb"
  ],
  "templateFolders": [
    "/Users/robmarscher/Code/rmarscher/replicator-cli/templates"
  ],
  "appConfigFilename": "replicator.json",
  "templateConfigFilename": "replicator.template.json",
  "replayConfigFilename": "replicator.replay.json",
  "patchFilename": "patch"
}
